modLoader = "javafml"
loaderVersion = "[34,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/Esberfes/mc-scarecrow-mod/issues"

[[mods]]
modId = "scarecrow"
version = "${file.jarVersion}"
displayName = "Scarecrow - Spawn Chunk Loder"
displayURL = "https://github.com/Esberfes/mc-scarecrow-mod"
logoFile = "examplemod.png"
authors = "esberfes and aorek"

description = '''
A chunk loader that keeps mob spawning active ...
'''

[[dependencies.scarecrow]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scarecrow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3]"
ordering = "NONE"
side = "BOTH"

[[dependencies.wawla]]
modId = "waila"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"